# Generated by Django 3.1.4 on 2020-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Enter your email')),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='last Name')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('is_company', models.BooleanField(default=False, verbose_name='Company')),
                ('image', models.ImageField(blank=True, null=True, upload_to='admin/', verbose_name='Image')),
                ('role', models.CharField(blank=True, max_length=20, null=True, verbose_name='User Role')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
